import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ChakraProvider  } from '@chakra-ui/react'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Ohana - list',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <ChakraProvider>
        <body className={inter.className}>{children}</body>
      </ChakraProvider>
  )
}
